### PR TITLE
Support bluetooth-only publishing, browsing, and service resolving.

### PR DESCRIPTION
**Pull request by xaphod**
This is useful if you want to avoid advertising / consuming wifi, which has a severe degredation on wifi performance (because it causes the OS to put wifi into adhoc mode each second)

### CODE REVIEW

**Comment by rweichler** [comment]
oh wow. this is awesome.

**Comment by xaphod** [comment]
Thanks. I ended up moving Bluepeer to its own repo (xaphod/bluepeer) since it didn't fit in. So the net set of changes to this pull request should be that there's now a swift-compatible podspec (because HHService now supports building as dynamic framework), and you can set bluetoothOnly. Sorry for the open-source mess, i'm used to working for big companies so i'm not good at open-source :)

**Comment by tolo** [comment]
Nice work!

Great, I was going to suggest moving bluepeer to its own repo, better to
keep them separate I think.

On vacation now, but I'll try and merge your changes soon :)

Thanks!
Tobias

**Comment by tolo** [comment]
Just added a develop branch that adds support for restricting service discovery and publishing to Bluetooth only (among other things). Will merge to master and publish the cocoapod soon. 

Thanks again @xaphod!

**Pull request closed without merging**
